# Generated by Django 6.0.5 on 2026-05-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('proyecto', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Documento', 'Documento'), ('Imagen', 'Imagen'), ('Captura', 'Captura'), ('Informe', 'Informe'), ('Presentacion', 'Presentacion'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('archivo_url', models.URLField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('tamano_archivo', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
